/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author danig
 */
public class InterfazEmpleado extends javax.swing.JFrame {

    

    String url = "jdbc:mysql://localhost/parcial3";
    String user = "root";
    String pass = "";

    /**
     * Creates new form InterfazEmpleado
     */
    public InterfazEmpleado() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Restaurante Las Delicias");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonMenuNombre = new javax.swing.JButton();
        botonVentas = new javax.swing.JButton();
        botonMenuPrecio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("EMPLEADO");

        botonMenuNombre.setText("VER MENÚ POR NOMBRE");
        botonMenuNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuNombreActionPerformed(evt);
            }
        });

        botonVentas.setText("VENTAS");
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });

        botonMenuPrecio.setText("VER MENÚ POR PRECIO");
        botonMenuPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(botonVentas)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonMenuNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonMenuPrecio))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMenuNombre)
                    .addComponent(botonMenuPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(botonVentas)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMenuNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuNombreActionPerformed
        //creacion del menu de comidas rapidas
        

        


    }//GEN-LAST:event_botonMenuNombreActionPerformed

    private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasActionPerformed
        try {
            Connection con = DriverManager.getConnection(url, user, pass);
            PreparedStatement pst = con.prepareStatement("SELECT * FROM pedidosrestaurante");

            ResultSet result = pst.executeQuery();

            TreeMap<String, String> ventas = new TreeMap<>();

            while (result.next()) {
                ventas.put(result.getString("CLIENTE"), result.getString("PRODUCTO"));
            }
                JTextArea txtarea = new JTextArea(ventas.toString());
            JOptionPane.showMessageDialog(null, txtarea);
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_botonVentasActionPerformed

    private void botonMenuPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuPrecioActionPerformed
        MenuRapido hDeLaCasa = new MenuRapido("Hamburguesa de la casa", 8500, "hamburguesa", "Ketchup", false);
        MenuRapido perroGuardian = new MenuRapido("Perro guardian", 9500, "hot-dog", "ninguna", true);
        MenuRapido salchipapaSuprema = new MenuRapido("La mejor salchipapa de la ciudad", 11500, "salchipapa", "Ketchup, Mayonesa y rosada", false);
        MenuRapido alitas = new MenuRapido("Alitas voladoras", 10500, "alas", "Teriyaki", true);

        String precio1 = Double.toString(hDeLaCasa.getPrecio());
        String precio2 = Double.toString(perroGuardian.getPrecio());
        String precio3 = Double.toString(salchipapaSuprema.getPrecio());
        String precio4 = Double.toString(alitas.getPrecio());

        TreeMap<Double, String> precios = new TreeMap<>();
        precios.put(hDeLaCasa.getPrecio(), hDeLaCasa.getComida());
        precios.put(perroGuardian.getPrecio(), perroGuardian.getComida());
        precios.put(salchipapaSuprema.getPrecio(), salchipapaSuprema.getComida());
        precios.put(alitas.getPrecio(), alitas.getComida());

        JOptionPane.showMessageDialog(null, precios);
    }//GEN-LAST:event_botonMenuPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazEmpleado().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMenuNombre;
    private javax.swing.JButton botonMenuPrecio;
    private javax.swing.JButton botonVentas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
